name: Add Component
description: Request that a component be added to an existing page
title: "[ADD COMPONENT]"
labels: ["enhancement"]
assignees: []
body:
- type: textarea
  attributes:
    label: Which page is being modified? Where should the new component be placed?
    description: A clear and concise description of component location.
  validations:
    required: true
- type: textarea
  attributes:
    label: What component is being added? What data should component use? Why’s this component being added?
    description: Describe component details and purpose.
  validations:
    required: true
- type: textarea
  attributes:
    label: What view/interactivity is expected from the component? Is there an example?
    description: Describe how the component should react.
  validations:
    required: true
- type: textarea
  attributes:
    label: How would these changes be best implemented?
    description: Describe how you think these changes would be best implement. Include any warnings here.
- type: textarea
  attributes:
    label: Are there any dependencies (other tasks, PRs, or modules) that need to be resolved before this change can be implemented?
    description: Add any other context, links or screenshots here.
