name: Add Component
description: Request that a component be added to an existing page
title: "[ADD COMPONENT]"
labels: ["enhancement"]
assignees: []
body:
- type: textarea
  attributes:
    label: Which page needs the component?
    description: Where on the page page should the component go? If possible provide an example.
  validations:
    required: true
- type: textarea
  attributes:
    label: What component is being added?
    description: What data will this component need? Why is it being added?
  validations:
    required: true
- type: textarea
  attributes:
    label: How should the component look and behave?
    description: Explain how the component should work. If possible, give an example.
  validations:
    required: true
- type: textarea
  attributes:
    label: Any warnings, considerations, or dependencies?
    description: Note any additional information, such as tasks that must be completed first, or any other factors.
