name: Create Page
description: Request a new page
title: "[NEW PAGE]"
labels: ["enhancement"]
assignees: []
body:
- type: textarea
  attributes:
    label: Which component(s) will be on this page? What data will be shown? Where should the link(s) to this page be?
    description: Describe key UI elements.
  validations:
    required: true
- type: textarea
  attributes:
    label: What is the purpose of this page? What view/interactivity is expected? Is there an example?
    description: Describe how the page should look and react.
  validations:
    required: true
- type: textarea
  attributes:
    label: Are there any dependencies (other tasks, PRs, or modules) that need to be resolved before this change can be implemented?
    description: Add any other context, links or screenshots here.
