name: Create Page
description: Request a new page
title: "[NEW PAGE]"
labels: ["enhancement"]
assignees: []
body:
- type: textarea
  attributes:
    label: What will be on the page?
    description: List the elements and data to be displayed. Where should the link to this page go?
  validations:
    required: true
- type: textarea
  attributes:
    label: What’s the goal of this page?
    description: Explain how the page should look and what interactions are expected. Any examples?
  validations:
    required: true
- type: textarea
  attributes:
    label: Any prerequisites?
    description: - Are there other tasks, pull requests, or modules that should be completed first? Include any additional information or screenshots.
