name: Edit Component
description: Modify a specific component implementation
title: "[ADD COMPONENT]"
labels: ["enhancement"]
assignees: []
body:
- type: textarea
  attributes:
    label: Which component needs changes?
    description: Specify which component is being updated and why.
  validations:
    required: true
- type: textarea
  attributes:
    label: What should the updated component do?
    description: Describe what the updated component should look like or how it should behave. If possible, provide an example.
  validations:
    required: true
- type: textarea
  attributes:
    label: Any warnings, considerations, or dependencies?
    description: Note any additional information, such as tasks that must be completed first, or any other factors.
